#!/usr/bin/env bash

# currently only handles python files
# TODO: add support for other languages; add step to compile python file in a "compressed" executable

# Check if the correct number of arguments is provided
if [ "$#" -ne 2 ]; then
  echo "Usage: $0 input_python_file output_python_file"
  exit 1
fi

# Assign input arguments to variables
input_file="$1"
output_file="$2"

# Define the shebang line
shebang_line="#!/usr/bin/env python3"

# Prepend the shebang line and save to the new file
{
  echo "$shebang_line"
  cat "$input_file"
} > "$output_file"

# Make the output file executable
chmod +x "$output_file"

